### ISSUE TITLE
Http clickthrough prevents puz gereration

### ISSUE THREAD

**Issue by deliciouslysmug** [Q726kbXuN/nytxw_puz#19]
The http version of the crossword now serves up a popup with class="xwd__modal--body xwd__start-modal" and a button to proceed with class="pz-moment__button". I believe those have to be acted upon before being able to access the puzzle information.

At the current moment, it appears that .puz generation of NYT is broken.

**Comment by Q726kbXuN** [comment]
@deliciouslysmug Which version of nytxw_puz are you using?

**Comment by Q726kbXuN** [comment]
![image](https://user-images.githubusercontent.com/79105979/160041998-8cbbfc62-099e-4961-be29-c25c7ea54114.png)

The latest version looks good to me, can you verify if there are still issues running 1.06 ?

**Comment by deliciouslysmug** [comment]
So sorry! Missed the 1.06 release. Closing this issue! Great job :)

**Comment by buszidog** [comment]
Wah! Version 1.06 didn't work on today's (Sunday) puzzle. It worked on this Friday's and Saturday's, last week's Sunday and the Sunday before. 
Agh, what, is the NYT planting bombs in it?




"I can't remember being a baby and I put that down to it being boring."
-Karl Pilkington











 

    On Thursday, March 24, 2022, 10:23:16 PM EDT, Q726kbXuN ***@***.***> wrote:  
 
 




The latest version looks good to me, can you verify if there are still issues running 1.06 ?

**Comment by edsantiago** [comment]
@buszidog just `git-fetch`. Last night's c40e88e commit (untagged) fixes the issues with today's NYT.

**Comment by buszidog** [comment]
GitHub/code dummy here(geez, I'm gonna be 75, have mercy!), how do I include/amend/drop this into nyt_puz v. 1.06?Thank you, thank you!

Loraine




"People moan about drugs being tested on animals. I sort of think it depends innit. If the drug's aspirin and the monkey's got a headache, is it right?" 
-Karl Pilkington











 

    On Sunday, March 27, 2022, 05:58:26 PM EDT, Ed Santiago ***@***.***> wrote:  
 
 


@buszidog just git-fetch. Last night's c40e88e commit (untagged) fixes the issues with today's NYT.

**Comment by Q726kbXuN** [comment]
@edsantiago That's hilarious.  The fix you're referencing was meant for an unrelated upcoming feature.  For once I'm ahead of the game.

@buszidog Try downloading the [pre-release of 1.07 from here](https://github.com/Q726kbXuN/nytxw_puz/releases/download/1.07/nytxw_puz.zip).  Let us know how it goes.

**Comment by buszidog** [comment]
It worked! Again, you're a genius. Thank you, thank you!
