### ISSUE TITLE
Sunday (May 1, 2022) grid is incorrect

### ISSUE THREAD

**Issue by jkboyce** [Q726kbXuN/nytxw_puz#21]
[Today's puzzle](https://www.nytimes.com/crosswords/game/daily/2022/05/01) is being parsed so that the grid is incorrect, which in turn makes the grid numbering and clue placement incorrect.

In the following grid answers, extra single black squares are being inserted (numberings are from the original NYT puzzle):

- 28 across
- 36 across
- 41 across
- 85 across
- 96 across
- 100 across
- 133 across
- 138 across

The issue may be related to the puzzle's note: "After you've finished solving, look for an appropriate bonus phrase."

**Comment by edsantiago** [comment]
Can you confirm that you're using 1.09 (2c5ad7f)?

**Comment by Q726kbXuN** [comment]
Please try downloading the [latest version](https://github.com/Q726kbXuN/nytxw_puz/releases), this issue should be fixed with version 1.09

**Comment by jkboyce** [comment]
Ah, upgrading to 1.09 fixed the issue. Thanks!
