### ISSUE TITLE
nyt-games-prd.appspot.com service returning "Forbidden"

### ISSUE THREAD

**Issue by hankscorpio83** [Q726kbXuN/nytxw_puz#25]
For example, for the 2021-08-31 puzzle, the response from https://nyt-games-prd.appspot.com/svc/crosswords/v6/puzzle/21315.json is `{"message":"Forbidden"}`

**Comment by Q726kbXuN** [comment]
Indeed, looks like the endpoint for all REST calls has changed to simply `www.nytimes.com`

I'll get a new build out tomorrow that fixes this.  Thanks for the report.

**Comment by Q726kbXuN** [comment]
Fixed with [1.13](https://github.com/Q726kbXuN/nytxw_puz/releases/tag/1.13)
